
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pegkfqfxedgfimklnbul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZ2tmcWZ4ZWRnZmlta2xuYnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTgyOTQsImV4cCI6MjA2MDI5NDI5NH0._XGAnXwF77pPe_Z07hg_YgEsL-cBJ8QArWPxISCi2Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
